# Generated by Django 2.2b1 on 2019-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20190316_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
    ]
