# Generated by Django 2.2b1 on 2019-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('contents', models.TextField()),
                ('hash', models.CharField(max_length=200)),
            ],
        ),
    ]
