# Generated by Django 2.2 on 2019-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('contents', models.TextField()),
                ('nonce', models.IntegerField(default=0)),
                ('hash', models.CharField(max_length=200)),
                ('signature', models.CharField(max_length=500)),
                ('pubkey', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
