# Generated by Django 2.2b1 on 2019-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pubkey',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.CharField(max_length=500),
        ),
    ]
