# Generated by Django 2.2b1 on 2019-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
    ]
